extensions:
    pim-catalog-volume-index:
        module: pim/common/simple-view
        config:
            template: pim/template/common/default-template

    pim-catalog-volume-index-grid-container:
        module: pim/common/simple-view
        parent: pim-catalog-volume-index
        targetZone: content
        config:
            template: pim/template/form/index/index

    pim-catalog-volume-index-user-navigation:
        module: pim/menu/user-navigation
        parent: pim-catalog-volume-index
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    pim-catalog-volume-index-grid-title:
        module: pim/common/grid-title
        parent: pim-catalog-volume-index
        targetZone: title
        config:
            title: pim_enrich.index.catalog_volume.title

    pim-catalog-volume-index-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: pim-catalog-volume-index
        targetZone: breadcrumbs
        config:
            tab: pim-menu-system
            item: pim-menu-system-catalog-volume