services:
    test.channel.builder:
        class: 'Pim\Acceptance\Channel\ChannelBuilder'
        arguments:
            - '@__symfony__.pim_catalog.factory.channel'
            - '@__symfony__.pim_catalog.updater.channel'
            - '@__symfony__.validator'

    test.locale.builder:
        class: 'Pim\Acceptance\Locale\LocaleBuilder'
        arguments:
            - '@__symfony__.pim_catalog.factory.locale'
            - '@__symfony__.pim_catalog.updater.locale'
            - '@__symfony__.validator'

    test.locale.context:
        class: 'Pim\Acceptance\Locale\LocaleContext'
        arguments:
            - '@__symfony__.pim_catalog.repository.locale'
            - '@test.locale.builder'
        tags:
            - { name: fob.context_service }

    test.channel.context:
        class: 'Pim\Acceptance\Channel\ChannelContext'
        arguments:
            - '@__symfony__.pim_catalog.repository.locale'
            - '@__symfony__.pim_catalog.repository.category'
            - '@__symfony__.pim_catalog.repository.channel'
            - '@test.channel.builder'
        tags:
            - { name: fob.context_service }
